### ISSUE TITLE
GetNetworkType error when targeting android 11 or above

### ISSUE THREAD

**Issue by rajdubeyetw** [HMS-Core/hms-video-editor-demo#18]
Hi there I am getting GetNetworkType error ( in Sdk Demo) while targeting android 11 or above.
Here is the complete crashlog please resolve this as soon as possible.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rvdapps.videoeditor/com.rvdapps.videoeditor.videoeditor.ui.mediaeditor.VideoClipsActivity}: java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3715)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3882)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:254)
        at android.app.ActivityThread.main(ActivityThread.java:8235)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
     Caused by: java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
        at android.os.Parcel.createException(Parcel.java:2373)
        at android.os.Parcel.readException(Parcel.java:2356)
        at android.os.Parcel.readException(Parcel.java:2298)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3024)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2988)
        at com.huawei.hms.videoeditor.sdk.hianalytics.f.a(HianalyticsLogUtils.java:8)
        at com.huawei.hms.videoeditor.sdk.hianalytics.event.BaseInfoGatherEvent.getCommonData(BaseInfoGatherEvent.java:9)
        at com.huawei.hms.videoeditor.sdk.hianalytics.event.BaseInfoGatherEvent.getEventData(BaseInfoGatherEvent.java:2)
        at com.huawei.hms.videoeditor.sdk.hianalytics.HianalyticsLogProvider.postEvent(HianalyticsLogProvider.java:17)
        at com.huawei.hms.videoeditor.sdk.HuaweiVideoEditor.initEnvironment(HuaweiVideoEditor.java:14)
        at com.rvdapps.videoeditor.videoeditor.ui.mediaeditor.VideoClipsActivity.initObject(VideoClipsActivity.java:383)
        at com.rvdapps.videoeditor.videoeditor.ui.mediaeditor.VideoClipsActivity.onCreate(VideoClipsActivity.java:296)
        at android.app.Activity.performCreate(Activity.java:8146)
        at android.app.Activity.performCreate(Activity.java:8130)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3684)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3882) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:254) 
        at android.app.ActivityThread.main(ActivityThread.java:8235) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by jianguo888** [comment]
你好，你的这个是咋配置 的https://github.com/HMS-Core/hms-video-editor-demo/issues/17
