### ISSUE TITLE
build.gradle里引入的gradle版本为3.4.3的，改成4.*.*以后的版本，运行报错崩溃

### ISSUE THREAD

**Issue by hp921001** [HMS-Core/hms-video-editor-demo#21]
3.4.3的版本太低了，与很多第三方包不兼容，有何处理办法，报错信息如下

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hpxksp.demo, PID: 15013
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libHuaweiMediaCreativity.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.huawei.hms.videoeditor.hmcbase.HmcBase.init(HmcBase.java:2)
        at com.huawei.hms.videoeditor.ui.api.MediaApplication.getInstance(MediaApplication.java:5)
        at com.huawei.videoeditorkit.videoeditdemo.MainActivity.initSetting(MainActivity.java:104)
        at com.huawei.videoeditorkit.videoeditdemo.MainActivity.onCreate(MainActivity.java:76)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/NetworkKit_HianalyticsHelper: main|HianalyticsHelper.java|com.huawei.hms.framework.common.hianalytics.HianalyticsHelper|isEnableReportNoSeed|157|Hianalytics sdk need to be initialized
I/Process: Sending signal. PID: 15013 SIG: 9

**Comment by hp921001** [comment]
发现是改变版本后，虚拟机运行崩溃，真机调试没问题
